on:
  pull_request:

concurrency:
  group: rtdworkflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@main
    secrets: inherit
    with:
      enable-sphinx-python-dependency-build-checks: false